# Generated by Django 4.2.30 on 2026-05-16 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_announcement_companysetting_distributor_invoice_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companysetting',
            name='two_factor_enabled',
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='company_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='currency',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='password_expiry_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='session_timeout_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_hours',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='companysetting',
            name='support_phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
