# Generated by Django 4.2.30 on 2026-05-17 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_companysetting_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='icon_type',
            field=models.CharField(default='megaphone', help_text='e.g. megaphone, calendar, bell', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='severity_label',
            field=models.CharField(blank=True, help_text='e.g. High, Medium, Low', max_length=50),
        ),
        migrations.AddField(
            model_name='announcement',
            name='tag_label',
            field=models.CharField(default='Notice', help_text='e.g. Product Launch, Notice, Event, Alert', max_length=50),
        ),
    ]
